### ISSUE TITLE
when exec 'npm start', it throw a error

### ISSUE THREAD

**Issue by cola-sk** [kdzwinel/betwixt#17]
``` fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'xxx/betwixt/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/xxx/cloned/betwixt/node_modules/electron-prebuilt/index.js:4:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by kdzwinel** [comment]
Not sure what causes that, but it seems to be an [electron issue](https://github.com/shockone/black-screen/issues/116). Try `rm -rf node_modules && npm install`.

**Comment by xiaotianhu** [comment]
same issuse,reinstall and solved.thanks

**Comment by kdzwinel** [comment]
@xiaotianhu thanks for letting me know. I'm closing the issue. If there is something I can do to fix it permanently for everyone, let me know.

**Comment by cola-sk** [comment]
thanks, i have solved this issue, `cd node_modules/electron-prebuilt`, and `npm install`
