### ISSUE TITLE
Node Issue - ENOENT: no such file or directory

### ISSUE THREAD

**Issue by bansipatel90** [kdzwinel/betwixt#45]
When i run node project i am facing below issue in ubantu.
How can I Solve this issue ? 

return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

Error: ENOENT: no such file or directory, open '../conf/log4j_config.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at loadConfigurationFile (Git-Dev/node_modules/log4js/lib/log4js.js:274:26)
    at Object.configure (Git-Dev/node_modules/log4js/lib/log4js.js:338:14)
    at Object.<anonymous> (Git-Dev/lib/logger.js:8:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by kdzwinel** [comment]
Thanks for reporting!

Please let me know:

- how you installed betwixt,
- which platform you are running (OSX, Win, Linux), 
- step by step what you are doing to get this error.
